name: Linux tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    name: Linux Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'ubuntu'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install System Packages
        run: | 
          sudo apt-get update --fix-missing
          sudo apt-get install -qq pyqt5-dev-tools libxcb-xinerama0 --fix-missing
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.PYTHON_VERSION }}
          channels: conda-forge
          channel-priority: strict
          miniforge-variant: Mambaforge
      - name: Install package dependencies
        shell: bash -l {0}
        run: mamba install --file requirements/conda.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: mamba install --file requirements/tests.txt -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Set up notebook server
        shell: bash -l {0}
        run: |
          cd spyder_notebook/server
          jlpm install
          jlpm build
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum pytest spyder_notebook --cov=spyder_notebook --color=yes -x -vv
        timeout-minutes: 10
      - name: Upload coverage to Codecov
        if: matrix.PYTHON_VERSION == '3.8'
        shell: bash -l {0}
        run: codecov -t dd249610-b0a4-42f6-bcfa-e7968f836790
